In [15]:
# there are many types of classifiers like artificial neural network ,support vector machines
# but we started with decision tree as they are very easy to read and understand




# in this notebook we'll use iris data set .. which is a classic ML problem


# in this you have identify different kinds of flowers based on their measurements
# we'll be classifying our output in three categories of flowers


# https://en.wikipedia.org/wiki/Iris_flower_data_set
# this data set is also availaible in the sklearn library.. which is easier to import

In [16]:
from sklearn.datasets import load_iris
iris=load_iris()

In [17]:
#this data set includes both the table from wikipedia and all also metadata
# the metadata tells the name of the fetaures and the names of the different  types of flowers
# the features and the examples themselves are contained in the "data"  variable



# https://en.wikipedia.org/wiki/Iris_flower_data_set

In [18]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
print(iris.target_names)




# these are the 3 species of the flower , in the output

['setosa' 'versicolor' 'virginica']


In [20]:
print(iris.data[0])



# 5.1 is sepal length and 3.5 is sepal width ..and so on

[5.1 3.5 1.4 0.2]


In [21]:
print(iris.target[0])


# label 0 means it's setosa and 1 means versicolor and 2 is virginica

0


In [23]:
print(iris.target[116])

2


In [26]:
# both the data and the target variable have a 150 entries
# to print out the entire data set .. use iteration

for i in range(1,150) :
    print("example : %d label: %s features: %s",i, iris.target[i], iris.data[i])

example : %d label: %s features: %s 1 0 [4.9 3.  1.4 0.2]
example : %d label: %s features: %s 2 0 [4.7 3.2 1.3 0.2]
example : %d label: %s features: %s 3 0 [4.6 3.1 1.5 0.2]
example : %d label: %s features: %s 4 0 [5.  3.6 1.4 0.2]
example : %d label: %s features: %s 5 0 [5.4 3.9 1.7 0.4]
example : %d label: %s features: %s 6 0 [4.6 3.4 1.4 0.3]
example : %d label: %s features: %s 7 0 [5.  3.4 1.5 0.2]
example : %d label: %s features: %s 8 0 [4.4 2.9 1.4 0.2]
example : %d label: %s features: %s 9 0 [4.9 3.1 1.5 0.1]
example : %d label: %s features: %s 10 0 [5.4 3.7 1.5 0.2]
example : %d label: %s features: %s 11 0 [4.8 3.4 1.6 0.2]
example : %d label: %s features: %s 12 0 [4.8 3.  1.4 0.1]
example : %d label: %s features: %s 13 0 [4.3 3.  1.1 0.1]
example : %d label: %s features: %s 14 0 [5.8 4.  1.2 0.2]
example : %d label: %s features: %s 15 0 [5.7 4.4 1.5 0.4]
example : %d label: %s features: %s 16 0 [5.4 3.9 1.3 0.4]
example : %d label: %s features: %s 17 0 [5.1 3.5 1.4 0.3]
exampl

In [27]:
# now we start with training the data set
# and we'll segregate the dataset.. one is for training and the other for testing 

In [30]:
import numpy as np
test_idx=[0,50,100]

# we chose 0, 50, 100 indexes because we know that our data set is ordered .. so we can use these 3 different indexes to get 
# different target values for each .. hence we'll testing our model on 3 different ecxpected output.






# training data 

train_target=np.delete(iris.target,test_idx)
train_data=np.delete(iris.data,test_idx,axis=0)

# numpy.delete(array, object, axis = None) : returns a new array with the deletion of sub-arrays along with the mentioned axis.





# testing data


test_target=iris.target[test_idx]
test_data=iris.data[test_idx]

# passing list as an argument to another function






from sklearn import tree
clf=tree.DecisionTreeClassifier()
clf.fit(train_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
print(test_target)

[0 1 2]


In [35]:
print(clf.predict(test_data))


# the predicted labels match the testing labels 
# hence the output is correct

[0 1 2]


In [44]:
# visualizing the decision tree so as to understand the working .. and more so over decision tree is a interpretable classifier
# not a part of machine learning


from sklearn.externals.six import StringIO
import pydot
dot_data=StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True , rounded =True,
                    impurity =False)
graph=pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

AttributeError: 'list' object has no attribute 'write_pdf'